version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    ports: ['27017:27017']
  redis:
    image: redis:7
    ports: ['6379:6379']
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/converter
      - REDIS_URL=redis://redis:6379
      - UPLOAD_DIR=./uploads
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports: ['3000:3000']
    depends_on: ['mongo','redis']
  worker:
    build: ./backend
    command: npm run worker
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/converter
      - REDIS_URL=redis://redis:6379
      - UPLOAD_DIR=./uploads
    depends_on: ['mongo','redis']
volumes:
  mongo_data:
